[package]
name = "berbir-engine"
version.workspace = true
edition.workspace = true

[dependencies]
berbir-shared = { path = "../shared" }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
uuid.workspace = true
tokio.workspace = true
reqwest.workspace = true
regex.workspace = true
tracing.workspace = true
thiserror = "2"
chrono.workspace = true
url.workspace = true

[features]
default = ["rustscan"]
rustscan = []
